#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
find packages/ -maxdepth 1 -type d -name 'foo*' -o -name 'bar*' | xargs -I % sh -c "cd % && npx auto-changelog --output CHANGELOG.md"
git add ./packages/*/CHANGELOG.md
npm run commitlint
